from random import choice

# Credit: https: // grammar.yourdictionary.com/parts-of-speech/adjectives/list-of-positive-adjectives.html
adjectives = ["Adaptable", "Adept", "Affectionate", "Agreeable", "Alluring", "Amazing", "Ambitious", "Amiable", "Ample", "Approachable", "Awesome", "Blithesome", "Bountiful", "Brave", "Breathtaking", "Bright", "Brilliant", "Capable", "Captivating", "Charming", "Competitive", "Confident", "Considerate", "Courageous", "Creative", "Customer-focused", "Dazzling", "Determined", "Devoted", "Diligent", "Diplomatic", "Dynamic", "Educated", "Efficient", "Elegant", "Enchanting", "Energetic", "Engaging", "Engrossing", "Excellent", "Fabulous", "Faithful", "Fantastic", "Fast-paced", "Favorable", "Fearless", "Flexible", "Focused", "Fortuitous", "Frank", "Friendly", "Funny", "Generous", "Giving", "Gleaming", "Glimmering", "Glistening", "Glittering", "Glowing", "Gorgeous", "Gregarious", "Gripping", "Hardworking", "Heart-warming", "Helpful", "Hilarious", "Honest", "Humorous",
              "Imaginative", "Imaginative", "Incredible", "Independent", "Inquisitive", "Insightful", "Kind", "Knowledgeable", "Likable", "Lovely", "Loving", "Loyal", "Lustrous", "Magnificent", "Marvelous", "Mirthful", "Moving", "Nice", "Open-minded", "Optimistic", "Organized", "Outstanding", "Passionate", "Patient", "Perfect", "Persistent", "Personable", "Philosophical", "Plucky", "Polite", "Powerful", "Productive", "Proficient", "Propitious", "Qualified", "Ravishing", "Relaxed", "Remarkable", "Resourceful", "Responsible", "Romantic", "Rousing", "Self-confident", "Sensible", "Shimmering", "Shining", "Sincere", "Sleek", "Sparkling", "Spectacular", "Spellbinding", "Splendid", "Stellar", "Stunning", "Stupendous", "Super", "Technological", "Thought-provoking", "Thoughtful", "Twinkling", "Unique", "Upbeat", "Vibrant", "Vivacious", "Vivid", "Warmhearted", "Willing", "Wondrous", "Zestful"]
# Credit: https: // en.wikipedia.org/wiki/List_of_animal_names
names = ["Aardvark", "Albatross", "Alligator", "Alpaca", "Anole", "Ant", "Anteater", "Antelope", "Ape", "Armadillo", "Ass", "Baboon", "Badger", "Barracuda", "Bat", "Bear", "Beaver", "Bee", "Beetle", "Binturong", "Bird", "Bison", "Bluebird", "Boar", "Bobcat", "Budgerigar", "Buffalo", "Butterfly", "Camel", "Capybara", "Caracal", "Caribou", "Cassowary", "Cat", "Caterpillar", "Cattle", "Chamois", "Cheetah", "Chicken", "Chimpanzee", "Chinchilla", "Chough", "Coati", "Cobra", "Cockroach", "Cod", "Cormorant", "Cougar", "Coyote", "Crab", "Crane", "Cricket", "Crocodile", "Crow", "Cuckoo", "Curlew", "Deer", "Dhole", "Dingo", "Dinosaur", "Dog", "Dogfish", "Dolphin", "Donkey", "Dove", "Dragonfly", "Duck", "Dugong", "Dunlin", "Eagle", "Echidna", "Eel", "Eland", "Elephant", "Elephant", "Elk", "Emu", "Falcon", "Ferret", "Finch", "Fish", "Fisher", "Flamingo", "Fly", "Flycatcher", "Fox", "Frog", "Gaur", "Gazelle", "Gecko", "Genet", "Gerbil", "Giant", "Giraffe", "Gnat", "Gnu", "Goat", "Goldfinch", "Goosander", "Goose", "Gorilla", "Goshawk", "Grasshopper", "Grouse", "Guanaco", "Guinea", "Guinea", "Gull", "Hamster", "Hare", "Hawk", "Hedgehog", "Hermit", "Heron", "Herring", "Hippopotamus", "Hoatzin", "Hoopoe", "Hornet", "Horse", "Human", "Hummingbird", "Hyena", "Ibex", "Ibis", "Iguana", "Impala", "Jackal", "Jaguar", "Jay", "Jellyfish", "Jerboa", "Kangaroo", "Kingbird", "Kingfisher", "Kinkajou", "Kite", "Koala", "Kodkod", "Komodo", "Kookaburra",
         "Kouprey", "Kudu", "Langur", "Lapwing", "Lark", "Lechwe", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster", "Locust", "Loris", "Louse", "Lynx", "Lyrebird", "Macaque", "Macaw", "Magpie", "Mallard", "Mammoth", "Manatee", "Mandrill", "Margay", "Marmoset", "Marmot", "Meerkat", "Mink", "Mole", "Mongoose", "Monkey", "Moose", "Mosquito", "Mouse", "Myna", "Narwhal", "Newt", "Nightingale", "Nilgai", "Ocelot", "Octopus", "Okapi", "Oncilla", "Opossum", "Orangutan", "Oryx", "Ostrich", "Otter", "Ox", "Owl", "Oyster", "Panther", "Parrot", "Panda", "Partridge", "Peafowl", "Pelican", "Penguin", "Pheasant", "Pig", "Pigeon", "Pika", "Polar", "Pony", "Porcupine", "Porpoise", "Prairie", "Pug", "Quail", "Quelea", "Quetzal", "Rabbit", "Raccoon", "Ram", "Rat", "Raven", "Red", "Red", "Reindeer", "Rhea", "Rhinoceros", "Rook", "Saki", "Salamander", "Salmon", "Sand", "Sandpiper", "Sardine", "Sassaby", "Sea", "Seahorse", "Seal", "Serval", "Shark", "Sheep", "Shrew", "Shrike", "Siamang", "Skink", "Skipper", "Skunk", "Sloth", "Snail", "Snake", "Spider", "Spoonbill", "Squid", "Squirrel", "Starfish", "Starling", "Stilt", "Swan", "Tamarin", "Tapir", "Tarsier", "Termite", "Thrush", "Tiger", "Toad", "Topi", "Toucan", "Turaco", "Turkey", "Turtle", "Vicu", "Vinegaroon", "Viper", "Vulture", "Wallaby", "Walrus", "Wasp", "Water", "Waxwing", "Weasel", "Whale", "Wildebeest", "Wobbegong", "Wolf", "Wolverine", "Wombat", "Woodpecker", "Worm", "Wren", "Yak", "Zebra"]


def generateName():
    return choice(adjectives) + " " + choice(names)
